ensuro/ensuro

- .github/workflows/tests.yaml
- .prettierignore
- brownie-config.yaml
- ci-tests.sh
- contracts/EToken.sol
- contracts/PolicyNFT.sol
- contracts/PolicyPool.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/mocks/TestCurrency.sol
- hardhat.config.js
- interfaces/IMintable.sol
- package-lock.json
- package.json
- prototype/ensuro.py
- prototype/utils.py
- tests/test_policypool.py
- tests/wrappers.py
Support for upgradeable contracts using UUPS proxy pattern and
OpenZeppelin libraries.
Implemented for now in RiskModule
> Upgradeable contracts

- contracts/BaseAssetManager.sol
- contracts/EToken.sol
- contracts/PolicyPool.sol
- contracts/mocks/FixedRateAssetManager.sol
- contracts/mocks/IMintableERC20.sol
- contracts/mocks/PolicyPoolMock.sol
- contracts/mocks/TestCurrency.sol
- interfaces/IAssetManager.sol
- interfaces/IMintable.sol
- interfaces/IPolicyPool.sol
- prototype/ensuro.py
- prototype/utils.py
- prototype/wadray.py
- tests/test_policypool.py
- tests/wrappers.py
Implementation of the asset manager in Solidity (work in progress)
> Asset Manager implementation

- contracts/EToken.sol
- contracts/LPManualWhitelist.sol
- contracts/PolicyPoolConfig.sol
- interfaces/ILPWhitelist.sol
- interfaces/IPolicyPoolConfig.sol
- prototype/contracts.py
- prototype/ensuro.py
- tests/test_etoken.py
- tests/test_policypool.py
- tests/wrappers.py
Interface ILPWhitelist plugs a contract to whitelist or not individual
addresses. The address are validated before deposit and also for
receiving transfers.
If ILPWhitelist is address(0), any address can deposit.
Initial implementation is manual whitelisting by authorized address.
> Liquidity Providers Whitelisting

- .github/workflows/tests.yaml
- brownie-config.yaml
- contracts/AaveAssetManager.sol
- contracts/BaseAssetManager.sol
- contracts/EToken.sol
- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PolicyPoolConfig.sol
- contracts/mocks/FixedRateAssetManager.sol
- contracts/mocks/PolicyPoolMock.sol
- hardhat.config.js
- interfaces/IPolicyPool.sol
- package-lock.json
- package.json
- tests/test_aave_assetmanager.py
- tests/test_assetmanager.py
- tests/wrappers.py
This PR will include the implementation of an AssetManager using AAVE.
Will invest the money in AAVE AToken and also convert the rewards into our underlying currency when deinvesting.
(WORK IN PROGRESS)
> AAVE Asset Manager

- .github/workflows/tests.yaml
- Dockerfile
- contracts/AaveAssetManager.sol
- contracts/BaseAssetManager.sol
- contracts/EToken.sol
- contracts/FlyionRiskModule.sol
- contracts/LPManualWhitelist.sol
- contracts/PolicyNFT.sol
- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PolicyPoolConfig.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/mocks/FixedRateAssetManager.sol
- contracts/mocks/PolicyPoolMock.sol
- deploySmokeTest.sh
- interfaces/IPolicyPool.sol
- package-lock.json
- package.json
- prototype/wrappers.py
- tasks/deploy.js
- tests/test_aave_assetmanager.py
Use immutable attributes set in constructor for fields that don't change
in contract lifetime.
Update to latest OZ-updates library that supports constructorArgs.
Remove events Deposit and Withdraw to decrease size of PolicyPool (not
needed because ETokens anyway emit similar events as Transfer with
address(0) in `from` on Deposit and `to` on Withdraw.
> Immutable attributes

- README.md
- contracts/AaveAssetManager.sol
- contracts/BaseAssetManager.sol
- contracts/DataTypes.sol
- contracts/EToken.sol
- contracts/FlightDelayRiskModule.sol
- contracts/LPManualWhitelist.sol
- contracts/Policy.sol
- contracts/PolicyNFT.sol
- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PolicyPoolConfig.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/WadRayMath.sol
- deploySmokeTest.sh
- tasks/deploy.js
Improved documentation of all the contracts and added security-contact.
Also, I've removed unused state variable _cashBalance in BaseAssetManager.
Added deploy script for Whitelist.
> Documentation and remove unused variable

- contracts/BaseAssetManager.sol
- prototype/ensuro.py
- tests/test_policypool.py
> Test case asset manager

- contracts/EToken.sol
- contracts/PolicyPool.sol
- contracts/RiskModule.sol
- contracts/upgraded/IPolicyNFTv1.sol
- contracts/upgraded/PolicyNFTv1.sol
- interfaces/IRiskModule.sol
- test/test-upgrade-aave-assetmanager.js
- test/test-upgrade-nft.js
- test/test-utils.js
- tests/test_policypool.py
Tests and storage compatibled contracts to upgrade deployed contracts.
> Deterministic PolicyId - Tests & upgrade contracts

- .gitignore
- contracts/FlightDelayRiskModule.sol
- contracts/PolicyPool.sol
- contracts/PremiumsAccount.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/extras/PriceRiskModule.sol
- contracts/mocks/FreeGrantInsolvencyHook.sol
- contracts/mocks/PolicyPoolComponentMock.sol
- contracts/mocks/PolicyPoolMock.sol
- deploySmokeTest-fork.sh
- deploySmokeTest.sh
- interfaces/IPolicyPool.sol
- interfaces/IPremiumsAccount.sol
- interfaces/IRiskModule.sol
- prototype/ensuro.py
- prototype/utils.py
- prototype/wrappers.py
- tasks/deploy.js
- test/test-price-risk-module.js
- test/test-upgrade-aave-assetmanager.js
- test/test-utils.js
- tests/test_flightdelayrm.py
- tests/test_policypool.py
- tests/test_riskmodule.py
Takes premiums to a different contract
WORK IN PROGRESS
> Premium Accounts

- contracts/EToken.sol
- contracts/PolicyPool.sol
- contracts/PremiumsAccount.sol
- contracts/Reserve.sol
- contracts/RiskModule.sol
- interfaces/IEToken.sol
- interfaces/IPremiumsAccount.sol
- prototype/ensuro.py
- prototype/wrappers.py
- tasks/deploy.js
- tests/__init__.py
- tests/test_etoken.py
- tests/test_flightdelayrm.py
- tests/test_policypool.py
- tests/test_riskmodule.py
The actual USD now is managed by each eToken instead of the PolicyPool.
Work in progress, missing Solidity Code.
> Segregated reserves

- contracts/FlightDelayRiskModule.sol
- contracts/PolicyPoolComponent.sol
- contracts/PolicyPoolConfig.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/extras/PriceRiskModule.sol
- interfaces/IPolicyPoolConfig.sol
- prototype/ensuro.py
- prototype/wrappers.py
- requirements-dev.txt
- requirements.txt
- tasks/deploy.js
- test/test-price-risk-module.js
- test/test-utils.js
- tests/test_flightdelayrm.py
- tests/test_policypool.py
- tests/test_riskmodule.py
Components like RiskModule use PolicyPoolConfig access control with
*component roles*.
Component roles are roles created doing XOR between the component
address and the original role.
> Only PolicyPoolConfig holds access control

- instrumented/coverage.js
> Exclude mocks and dependency contracts from coverage reporting

- contracts/AccessManager.sol
- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PremiumsAccount.sol
- contracts/RiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/mocks/PolicyHolderMock.sol
> Change to use _msgSender() instead of msg.sender

- .github/workflows/tests.yaml
- contracts/SignedQuoteRiskModule.sol
- test/test-signed-quote-risk-module.js
Risk module where the pricing is validated by a signature.
Work in progress - Not yet tested.
> Signed Quote Risk Module

- contracts/HurricaneRiskModule.sol
Hurricane Risk Module - For Ensuro 1.1
> Hurricane risk module

- contracts/AccessManager.sol
- contracts/ERC4626AssetManager.sol
- contracts/EToken.sol
- contracts/LPManualWhitelist.sol
- contracts/LiquidityThresholdAssetManager.sol
- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PremiumsAccount.sol
- contracts/Reserve.sol
- contracts/RiskModule.sol
- contracts/SignedQuoteRiskModule.sol
- contracts/TrustfulRiskModule.sol
- contracts/interfaces/IAssetManager.sol
- scripts/storageLayout.js
- test/test-storage-gaps.js
- test/test-utils.js
Hardhat upgrades plugin will validate that we update the gap properly on upgrades: https://blog.openzeppelin.com/validate-smart-contract-storage-gaps-with-openzeppelin-upgrades-plugins/
I've also added a simple script to print out the storage layout for the contracts, which I used to validate I hadn't miscounted the used slots.
Below is the output for each contract.
```
Nothing to compile
┌─────────┬───────┬─────────────────┬─────────────────────────────────────────────────────┐
│ (index) │ slot  │      label      │                        type                         │
├─────────┼───────┼─────────────────┼─────────────────────────────────────────────────────┤
│    0    │  '0'  │ '_initialized'  │                      't_uint8'                      │
│    1    │  '0'  │ '_initializing' │ …
```
> Fix QSP-4 Upgradeable Contract Storage Gaps

- contracts/PolicyPool.sol
Change the order when the policy hash is deleted.
> QSP-15 Fix reentrancy attack in resolvePolicy

- contracts/PolicyPool.sol
- contracts/PolicyPoolComponent.sol
- contracts/PremiumsAccount.sol
- contracts/RiskModule.sol
- test/test-upgrade-permissions.js
Additional validation on upgrades to verify the immutable attributes aren't changed.
Only is accepted to change PremiumsAccount senior and junior eToken from 0 to != address(0).
> Validates Upgrades don't change immutable attrs

- prototype/wrappers.py
- tasks/deploy.js
> Fixes and improvements in deploy scripts

- test/test-add-remove-change-components.js
- test/test-policy-pool.js
- test/test-risk-module.js
- test/test-signed-quote-risk-module.js
- test/test-upgrade-permissions.js
- test/test-utils.js
PolicyPool upgrade wasn't tested. Also newPolicyFull endpoints and getPolicyHash.
> Improve test coverage

- tasks/deploy.js
- test/test-add-remove-change-components.js
- test/test-pause-unpause-permissions.js
- test/test-risk-module.js
- test/test-signed-quote-risk-module.js
- test/test-utils.js
- tests/test_riskmodule.py
- Fixes and changes to deploy.js to be able to use it from other projects.
- Change in test-utils to use exports dict at the end of the file.
- Moved functions of signed quotes to test-utils file and refactor some tests.
> Fixes and improvements to JS scripts

- .solhintignore
- contracts/RiskModule.sol
- contracts/SignedQuoteRiskModule.sol
- contracts/TieredSignedQuoteRiskModule.sol
- contracts/TrustfulRiskModule.sol
- hardhat.config.js
- prototype/ensuro.py
- prototype/wrappers.py
- tasks/deploy.js
- test/test-constructors.js
- test/test-signed-quote-risk-module.js
- test/test-storage-gaps.js
- test/test-supports-interface.js
- test/test-tiered-signed-riskmodule.js
- test/test-utils.js
- tests/test_tiered_risk_module.py
Adds risk module with support for multiple buckets of risk based on the lossprob.
> TieredSignedQuoteRiskModule

- contracts/RiskModule.sol
- contracts/SignedBucketRiskModule.sol
- test/test-initializers.js
- test/test-signed-bucket-riskmodule.js
- test/test-signed-quote-risk-module.js
- test/test-tiered-signed-riskmodule.js
- test/test-utils.js
New risk module that uses signed messages for validating the quote, that includes a bucketId identifiying the group of policies and the associated parameters to apply.
Work in progress
> Signed Bucket Risk Module

- .github/workflows/tests.yaml
- .solcover.js
- README.md
- test/test-constructors.js
Change in the coverage badge test generation.
> Fix Coverage Badge Test + new test ERC4626PlusVaultAssetManager

- contracts/PolicyPool.sol
- test/test-upgrade-permissions.js
Change in the PolicyPool contract to accept an upgrade that changes the currency().
> Change PolicyPool._authorizeUpgrate: currency can be changed

- contracts/FullSignedBucketRiskModule.sol
- js/utils.js
- test/test-full-signed-bucket-risk-module.js
Also, I add the function to make the same computation off-chain to utils.js
> New method to compute the min premium for full params
