ensuro/ensuro

contracts/Policy.sol
contracts/RiskModule.sol
contracts/TrustfulRiskModule.sol
interfaces/IRiskModule.sol
prototype/contracts.py
prototype/ensuro.py
prototype/wadray.py
tests/test_policypool.py
tests/test_riskmodule.py
tests/wrappers.py

New pricing strategy. Now each RiskModule has a fixed interest rate that
has to pay for the capital locked (SCR).
Also renamed `ensuro_share` to `ensuro_fee` and now is calculated as a
percentage of pure premium.
Finally, removed premium_share (the share for RM), because now that is
variable, is whatever exceeds the pure_premium + ensuro_fee + capital
cost.

New Pricing - interest rate fixed / RM variable

---

contracts/BaseAssetManager.sol
prototype/ensuro.py
tests/test_policypool.py

Now the operations of AssetManager that distribute earnings and
rebalance cash between the asset manager and the PolicyPool are open to
anyone who pays the gas.

Removing CHECKPOINT_ROLE required for AssetManager

---

contracts/PolicyPool.sol
prototype/ensuro.py
tests/test_policypool.py
tests/wrappers.py

`expirePolicy` is a public endpoint that can be called by anyone after
the policy expired. It resolves the policy with zero payout,
distributing the premiums and unlocking the SCR.
`withdrawWonPremiums` this endpoint is restricted to used with role
WITHDRAW_WON_PREMIUMS_ROLE and withdraws the won pure premiums to the
treasury. Can be disabled revoking the WITHDRAW_WON_PREMIUMS_ROLE.

Expire Policy and Withdraw Won Premiums

---

.dockerignore
.gitignore
contracts/AaveAssetManager.sol
contracts/BaseAssetManager.sol
contracts/DataTypes.sol
contracts/EToken.sol
contracts/PolicyNFT.sol
contracts/PolicyPool.sol
contracts/PolicyPoolConfig.sol
contracts/TrustfulRiskModule.sol
contracts/mocks/FreeGrantInsolvencyHook.sol
contracts/mocks/LPInsolvencyHook.sol
contracts/mocks/PolicyPoolMock.sol
hardhat.config.js
interfaces/IEToken.sol
interfaces/IInsolvencyHook.sol
interfaces/IPolicyPool.sol
interfaces/IPolicyPoolConfig.sol
package-lock.json
package.json
prototype/ensuro.py
prototype/utils.py
tasks/deploy.js
tests/test_aave_assetmanager.py
tests/test_policypool.py
tests/wrappers.py

Previously, lendToPool was only considering the ocean, leaving always
the SCR. Now, was a parameter to consider all the total supply. This can
lead to a situation where `SCR>totalSupply`, in those cases, we call the
InsolvencyHook to give the opportunity to solve this lack of SCR.
Other change, now PolicyPoolConfig and PolicyNFT accept the address of
the PolicyPool in the initialization. This allows pre-calculate the
address of PolicyPool (with CREATE2) and create PolicyPoolConfig and
PolicyNFT with that address already connected.

SCR insolvency / Config and NFT take pool address

---

contracts/EToken.sol
contracts/PolicyPool.sol
prototype/ensuro.py
prototype/wrappers.py
tests/test_etoken.py
tests/test_policypool.py

Rejects resolution with payout>0 if the policy has expired.
Also I had to fix many test cases because they were doing exactly that,
resolving with payout after (a few seconds usually) the expiration.

Forbid paid resolution of expired policies

---

contracts/FlightDelayRiskModule.sol
contracts/Policy.sol
contracts/PolicyPool.sol
contracts/RiskModule.sol
contracts/TrustfulRiskModule.sol
deploySmokeTest.sh
interfaces/IRiskModule.sol
prototype/ensuro.py
prototype/wrappers.py
tasks/deploy.js
tests/test_policypool.py
tests/test_riskmodule.py

We were supporting an option of "shared coverage", where the risk module
covers a given percentage of the payout and takes the same percentage of
the premium. That payout was taken upfront from the risk partner,
requiring full collateralization on their side.
We are not sure this will be used in practice, so I removed it to
simplify the code and reduce gas cost.

Remove Shared Coverage feature

---

tests/test_policypool.py

More test cases of partial payout
- when payout < premium and payout > (premium - policy.premium_for_lps)
- should take as pool loan (if the only policy) payout - (premium - premium_for_lps)
- when payout < premium and payout > (policy.pure_premium)
- should increase won_pure_premiums with payout - (premium - premium_for_lps)
- when payout < premium and payout <= (policy.pure_premium)
- should increase won_pure_premiums with payout - (premium - premium_for_lps)

Test cases of partial payout

---

.github/workflows/tests.yaml
contracts/FlightDelayRiskModule.sol
contracts/Policy.sol
contracts/PolicyNFT.sol
contracts/PolicyPool.sol
contracts/RiskModule.sol
contracts/TrustfulRiskModule.sol
contracts/mocks/PolicyPoolMock.sol
interfaces/IPolicyPool.sol
prototype/wrappers.py

Instead of storing the policies in the blockchain, I just store a hash.
For every operation that involves a Policy, the policy data needs to be
sent and is later validated comparing with the stored hash.
(partially implemented, still have to remove the Policy storage in
riskmodule contract)

Refactoring to save gas - Don't store policies

---

contracts/Policy.sol
contracts/RiskModule.sol
prototype/ensuro.py
prototype/wrappers.py
tests/test_policypool.py
tests/test_riskmodule.py

Previously the scr was:
`scr = (payout - premium) * scr_percentage`
This wasn't correct because even defining the `scr_percentage` as
`(VAR995-VAR50)/VAR100`, it wasn't the right value.
With that definition for the scr_percentage the right formula should be
`scr = payout * scr_percentage` (assuming premium == VAR50, that's not
true in general).
Instead of that, now the `scr_percentage` should be defined as
`VAR995/VAR100` (the proportion of the current colateralization level
with respect to full colateralization).
And the `scr` is now defined as:
`scr = payout * scr_percentage - premium`

Change in SCR computation

---

Dockerfile
contracts/FlightDelayRiskModule.sol
contracts/PolicyNFT.sol
contracts/PolicyPool.sol
contracts/RiskModule.sol
contracts/TrustfulRiskModule.sol
contracts/mocks/PolicyPoolMock.sol
deploySmokeTest-fork.sh
deploySmokeTest.sh
interfaces/IPolicyNFT.sol
interfaces/IPolicyPool.sol
prototype/ensuro.py
prototype/wrappers.py
tasks/deploy.js
tests/test_flightdelayrm.py
tests/test_policypool.py
tests/test_riskmodule.py

Before this change, the policyId number it's known only after the
newPolicy transaction is processed, because it was a counter in the
PolicyNFT contract.
This was a problem for partners integrating with us that need to avoid
duplicated policies and need to match their internal id with the
Ensuro's Policy Id.
With this change, the user needs to send a `internalId` parameter and
the resulting policyId is created merging this internalId with the Risk
Module address:
`policyId = uint256(riskModule.address) << 96 + internalId`
This way we can know in advance the policyId and at the same time we
avoid colission of the numbers between two different modules.

Deterministic Policy Id

---

contracts/PolicyPool.sol
prototype/ensuro.py
tests/test_policypool.py

Until now, the SCR of a policy was split between several eTokens. This
was adding a lot of complexity that's not really needed, since most of
the time just one eToken accepts a policy.
Now, each policy has a single solvency eToken. We still keep the
expiration limit at the eToken level, but now it's not so relevant.
Work in progress, change done only in the Python code, missing the
Solidity Code.

Removes horizonal SCR split

---

contracts/EToken.sol
contracts/PremiumsAccount.sol
contracts/RiskModule.sol
contracts/interfaces/IEToken.sol
contracts/interfaces/IPolicyPoolConfig.sol
contracts/interfaces/IPremiumsAccount.sol
contracts/interfaces/IRiskModule.sol
prototype/ensuro.py
prototype/wrappers.py
scripts/build-docs.sh
tests/test_etoken.py
tests/test_policypool.py

Pool is an ambigous name and we were using this because previously the
loads where given to the PolicyPool. Now are given to the premiums
accounts.
Also added some docs.

Renamed poolLoan to internalLoan

---

.github/workflows/npm.yaml
README.md
npm-package/package.json
scripts/make-npm-package.sh

We may omit the management of the version number and handle it directly on the package.json, but it seemed to be simple enough and is one less thing to worry about when releasing.

Npm upload

---

contracts/AccessManager.sol
contracts/EToken.sol
contracts/PolicyPool.sol
contracts/PolicyPoolComponent.sol
contracts/PremiumsAccount.sol
contracts/RiskModule.sol
test/test-implementation-disabled-init.js

Fix for the finding QSP-1 Uninitialized Implementation Contracts.
Work in progress.
So far we also fixed the internal initializer functions to use the `onlyInitializing` modifier instead of `initializer` that should be used only in top level function.

Fix QSP-1 Uninitialized Implementation Contracts

---

contracts/EToken.sol
contracts/PremiumsAccount.sol

Some functions were not following the Checks-Effects-Interactions pattern, opening to potential manipulations.
Also, copied the _spendAllowance function from OZ ERC20 to support non changing infinite allowance.

QSP-12 Checks-Effects-Interactions fix

---

contracts/EToken.sol
test/test-pause-unpause-permissions.js

Adds the modifier to prevent repayLoan to be called when the contract is paused.

QSP-20 Disable repayLoan when paused

---

contracts/PremiumsAccount.sol
prototype/ensuro.py
tests/test_premiumsaccount.py

Previous code was doing a max approval for both eTokens when this approval is only needed when the premium account has to repay a loan.
This was exposing PremiumsAccount to any possible compromise on eToken contracts.
Instead now we delay the approval until we have to repay a loan. In that case the approval is done for all the pending debt, with the expectation to avoid some approvals in the future.

QSP-17 Reverts max approval - Approves when needed

---

contracts/EToken.sol
prototype/ensuro.py
tests/test_etoken.py

Change in the withdraw function to revert if the amount required is more than the amount available to withdraw (unless MAX_UINT is sent as amount, in that case it will withdraw as much as possible).
Code changes only. TODO: fix the tests

Revert on exceeded withdraw

---

contracts/EToken.sol
contracts/LPManualWhitelist.sol
contracts/PremiumsAccount.sol
contracts/RiskModule.sol
contracts/TimeScaled.sol
contracts/interfaces/IAccessManager.sol
contracts/interfaces/IEToken.sol
prototype/ensuro.py
prototype/utils.py
prototype/wrappers.py
test/test-supports-interface.js
tests/test_etoken.py
tests/test_policypool.py
tests/test_premiumsaccount.py

Adds two new parameters to PremiumsAccount to be able to specify the limits on the loans taken from the Junior and Senior eToken. By default the loans are unbounded.
These parameters allow to define a hard limit on the propagation of losses to the eTokens, mainly to the senior one.
This could have been implemented on eToken side, but that would require a major refactoring, so we keep that for next versions.

Loss Propagation Limits

---

.github/workflows/npm.yaml
tests/test_riskmodule.py

Change done on RiskModule tests. The same suite is run with 6 and 18 decimals.
With these tests I verified the tweak checks on the exposure limit work well (the problem was that LEVEL1 is required to increase the exposure limit).

Parametrized tests using 6 or 18 decimals

---

contracts/RiskModule.sol

This can be called from risk modules that have different parameters for each policy, for example with levels of collateralization depending on the loss prob.

New internal function _newPolicyWithCustomParams

---

contracts/PremiumsAccount.sol
prototype/ensuro.py
prototype/wrappers.py
test/test-pause-unpause-permissions.js
test/test-supports-interface.js
test/test-upgrade-permissions.js
tests/test_policypool.py
tests/test_premiumsaccount.py

Previously it was trying to do the repayment of the loans automatically in each point of the code where a pure premium was won. This wasn't effective because it's a waste of resources when the PA is not in debt (most of the time). Also, when the PA is in debt this produces a lot of micro-payments increasing the gas usage and also making the PA more prone to take debt in the near term.
Now the debt repayment has been moved to a new public method. This can be called at any time given enough funds available.
Funds available are calculated as (surplus - _maxDeficit), so the PA will take as much deficit as needed to repay the debt.
Also in the previous version the debt was only repaid with won pure premiums. Given this change, it can be paid with pure premiums comming from new business. A good …

Refactor PremiumsAccount - Repayments on-demand

---

brownie-config.yaml
contracts/ERC4626AssetManager.sol
contracts/LiquidityThresholdAssetManager.sol
contracts/Reserve.sol
contracts/TimeScaled.sol
contracts/interfaces/IAssetManager.sol
prototype/ensuro.py
prototype/wrappers.py
tests/test_etoken.py

When unplugging an Asset Manager it was leaving the lastInvestmentValue with a wrong value. Then when a new Asset Manager is plugged, it reuses the same storage and assumes the lastInvestmentValue is different than the real value.

Fix DeinvestAll Bug

---

js/constants.js
js/enums.js
js/test-utils.js
js/utils.js
tasks/deploy.js

**IMPORTANT**: has to be merged after https://github.com/ensuro/ensuro/pull/160
- extraConstructorArgs in deploy:riskModule
- readImplementationAddress from deploy-scripts fixtures
- ComponentStatus enum from deploy-scripts `test/test-v26-policypool.js`
- fork/forkIt/skipForkTests from price-risk-module `test/utils.js`
- fork currency (impersonate whale+transfer or mint?)
- HOUR constant
- getBucketId from from deploy-scripts `changeset.js` -> renamed as uintKeccak
- Remove workaround for hardhat verify:verify on proxy contracts

Upstreaming of several utils and test-utils from other repos. Other improvements un utilities.

---

contracts/Policy.sol
contracts/PolicyPool.sol
contracts/PremiumsAccount.sol
contracts/RiskModule.sol
contracts/TrustfulRiskModule.sol
contracts/interfaces/IPolicyPool.sol
contracts/interfaces/IPremiumsAccount.sol
contracts/mocks/InterfaceIdCalculator.sol
contracts/mocks/PolicyPoolMock.sol
contracts/mocks/RiskModuleMock.sol
package-lock.json
prototype/ensuro.py
prototype/wrappers.py
test/test-add-remove-change-components.js
test/test-policy-pool.js
test/test-policy.js
test/test-risk-module.js
test/test-supports-interface.js
test/test-tiered-signed-riskmodule.js
tests/test_policypool.py

New feature to support the replacement of a policy with a new upgraded one. The new policy must be greater or equal than the previous one in several aspects:
- expiration
- payout
- pure_premium
- jr_coc and sr_coc
- ensuro_fee

Policy Replacement

---

contracts/ERC4626AssetManager.sol
contracts/ERC4626PlusVaultAssetManager.sol
prototype/ensuro.py
prototype/wrappers.py
test/test-constructors.js
test/test-supports-interface.js
tests/test_policypool.py

New asset manager that besides the default vault where most of the funds are invested, it can rebalance some funds to another vault, called "discretionary vault", because the rebalance only happens by admin calls.
The discretionary vault is used for covering payments only if the main vault is exhausted.

ERC4626PlusVaultAssetManager: asset manager with discretionary vault
